//
// Created by nexie on 20.12.2025.
//

#ifndef NX_MACRO_SEQUENCE_64_HPP
#define NX_MACRO_SEQUENCE_64_HPP

#ifndef NX_MACRO_PRIVATE_INCLUDE
    #error "This file was not meant to be included directly. Include <nx/macro/detail/sequence_limit.hpp> instead"
#endif

 # define _nx_sequence_0(...)
 # define _nx_sequence_1(c, h, m, ...) _nx_sequence_0(0, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 1, __VA_ARGS__))
 # define _nx_sequence_2(c, h, m, ...) _nx_sequence_1(0, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 2, __VA_ARGS__))
 # define _nx_sequence_3(c, h, m, ...) _nx_sequence_2(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 3, __VA_ARGS__))
 # define _nx_sequence_4(c, h, m, ...) _nx_sequence_3(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 4, __VA_ARGS__))
 # define _nx_sequence_5(c, h, m, ...) _nx_sequence_4(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 5, __VA_ARGS__))
 # define _nx_sequence_6(c, h, m, ...) _nx_sequence_5(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 6, __VA_ARGS__))
 # define _nx_sequence_7(c, h, m, ...) _nx_sequence_6(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 7, __VA_ARGS__))
 # define _nx_sequence_8(c, h, m, ...) _nx_sequence_7(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 8, __VA_ARGS__))
 # define _nx_sequence_9(c, h, m, ...) _nx_sequence_8(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 9, __VA_ARGS__))
 # define _nx_sequence_10(c, h, m, ...) _nx_sequence_9(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 10, __VA_ARGS__))
 # define _nx_sequence_11(c, h, m, ...) _nx_sequence_10(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 11, __VA_ARGS__))
 # define _nx_sequence_12(c, h, m, ...) _nx_sequence_11(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 12, __VA_ARGS__))
 # define _nx_sequence_13(c, h, m, ...) _nx_sequence_12(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 13, __VA_ARGS__))
 # define _nx_sequence_14(c, h, m, ...) _nx_sequence_13(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 14, __VA_ARGS__))
 # define _nx_sequence_15(c, h, m, ...) _nx_sequence_14(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 15, __VA_ARGS__))
 # define _nx_sequence_16(c, h, m, ...) _nx_sequence_15(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 16, __VA_ARGS__))
 # define _nx_sequence_17(c, h, m, ...) _nx_sequence_16(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 17, __VA_ARGS__))
 # define _nx_sequence_18(c, h, m, ...) _nx_sequence_17(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 18, __VA_ARGS__))
 # define _nx_sequence_19(c, h, m, ...) _nx_sequence_18(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 19, __VA_ARGS__))
 # define _nx_sequence_20(c, h, m, ...) _nx_sequence_19(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 20, __VA_ARGS__))
 # define _nx_sequence_21(c, h, m, ...) _nx_sequence_20(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 21, __VA_ARGS__))
 # define _nx_sequence_22(c, h, m, ...) _nx_sequence_21(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 22, __VA_ARGS__))
 # define _nx_sequence_23(c, h, m, ...) _nx_sequence_22(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 23, __VA_ARGS__))
 # define _nx_sequence_24(c, h, m, ...) _nx_sequence_23(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 24, __VA_ARGS__))
 # define _nx_sequence_25(c, h, m, ...) _nx_sequence_24(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 25, __VA_ARGS__))
 # define _nx_sequence_26(c, h, m, ...) _nx_sequence_25(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 26, __VA_ARGS__))
 # define _nx_sequence_27(c, h, m, ...) _nx_sequence_26(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 27, __VA_ARGS__))
 # define _nx_sequence_28(c, h, m, ...) _nx_sequence_27(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 28, __VA_ARGS__))
 # define _nx_sequence_29(c, h, m, ...) _nx_sequence_28(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 29, __VA_ARGS__))
 # define _nx_sequence_30(c, h, m, ...) _nx_sequence_29(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 30, __VA_ARGS__))
 # define _nx_sequence_31(c, h, m, ...) _nx_sequence_30(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 31, __VA_ARGS__))
 # define _nx_sequence_32(c, h, m, ...) _nx_sequence_31(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 32, __VA_ARGS__))
 # define _nx_sequence_33(c, h, m, ...) _nx_sequence_32(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 33, __VA_ARGS__))
 # define _nx_sequence_34(c, h, m, ...) _nx_sequence_33(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 34, __VA_ARGS__))
 # define _nx_sequence_35(c, h, m, ...) _nx_sequence_34(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 35, __VA_ARGS__))
 # define _nx_sequence_36(c, h, m, ...) _nx_sequence_35(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 36, __VA_ARGS__))
 # define _nx_sequence_37(c, h, m, ...) _nx_sequence_36(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 37, __VA_ARGS__))
 # define _nx_sequence_38(c, h, m, ...) _nx_sequence_37(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 38, __VA_ARGS__))
 # define _nx_sequence_39(c, h, m, ...) _nx_sequence_38(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 39, __VA_ARGS__))
 # define _nx_sequence_40(c, h, m, ...) _nx_sequence_39(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 40, __VA_ARGS__))
 # define _nx_sequence_41(c, h, m, ...) _nx_sequence_40(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 41, __VA_ARGS__))
 # define _nx_sequence_42(c, h, m, ...) _nx_sequence_41(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 42, __VA_ARGS__))
 # define _nx_sequence_43(c, h, m, ...) _nx_sequence_42(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 43, __VA_ARGS__))
 # define _nx_sequence_44(c, h, m, ...) _nx_sequence_43(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 44, __VA_ARGS__))
 # define _nx_sequence_45(c, h, m, ...) _nx_sequence_44(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 45, __VA_ARGS__))
 # define _nx_sequence_46(c, h, m, ...) _nx_sequence_45(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 46, __VA_ARGS__))
 # define _nx_sequence_47(c, h, m, ...) _nx_sequence_46(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 47, __VA_ARGS__))
 # define _nx_sequence_48(c, h, m, ...) _nx_sequence_47(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 48, __VA_ARGS__))
 # define _nx_sequence_49(c, h, m, ...) _nx_sequence_48(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 49, __VA_ARGS__))
 # define _nx_sequence_50(c, h, m, ...) _nx_sequence_49(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 50, __VA_ARGS__))
 # define _nx_sequence_51(c, h, m, ...) _nx_sequence_50(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 51, __VA_ARGS__))
 # define _nx_sequence_52(c, h, m, ...) _nx_sequence_51(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 52, __VA_ARGS__))
 # define _nx_sequence_53(c, h, m, ...) _nx_sequence_52(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 53, __VA_ARGS__))
 # define _nx_sequence_54(c, h, m, ...) _nx_sequence_53(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 54, __VA_ARGS__))
 # define _nx_sequence_55(c, h, m, ...) _nx_sequence_54(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 55, __VA_ARGS__))
 # define _nx_sequence_56(c, h, m, ...) _nx_sequence_55(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 56, __VA_ARGS__))
 # define _nx_sequence_57(c, h, m, ...) _nx_sequence_56(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 57, __VA_ARGS__))
 # define _nx_sequence_58(c, h, m, ...) _nx_sequence_57(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 58, __VA_ARGS__))
 # define _nx_sequence_59(c, h, m, ...) _nx_sequence_58(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 59, __VA_ARGS__))
 # define _nx_sequence_60(c, h, m, ...) _nx_sequence_59(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 60, __VA_ARGS__))
 # define _nx_sequence_61(c, h, m, ...) _nx_sequence_60(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 61, __VA_ARGS__))
 # define _nx_sequence_62(c, h, m, ...) _nx_sequence_61(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 62, __VA_ARGS__))
 # define _nx_sequence_63(c, h, m, ...) _nx_sequence_62(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 63, __VA_ARGS__))
 # define _nx_sequence_64(c, h, m, ...) _nx_sequence_63(1, h, m, __VA_ARGS__)  h(c, _nx_apply(m, 64, __VA_ARGS__))

#define NX_LIMITS_SEQUENCE 64

#endif //NX_MACRO_ITERATE_64_HPP
