//
// Created by nexie on 20.12.2025.
//

#ifndef NX_MACRO_SEQUENCE_64_HPP
#define NX_MACRO_SEQUENCE_64_HPP

#define _nx_sequence_0(c, h, m, ...)
#define _nx_sequence_1(c, h, m, ...)   _nx_sequence_0(0, h, m, __VA_ARGS__) h(c, m, 1, __VA_ARGS__)
#define _nx_sequence_2(c, h, m, ...)   _nx_sequence_1(0, h, m, __VA_ARGS__) h(c, m, 2, __VA_ARGS__)
#define _nx_sequence_3(c, h, m, ...)   _nx_sequence_2(0, h, m, __VA_ARGS__) h(c, m, 3, __VA_ARGS__)
#define _nx_sequence_4(c, h, m, ...)   _nx_sequence_3(0, h, m, __VA_ARGS__) h(c, m, 4, __VA_ARGS__)
#define _nx_sequence_5(c, h, m, ...)   _nx_sequence_4(0, h, m, __VA_ARGS__) h(c, m, 5, __VA_ARGS__)
#define _nx_sequence_6(c, h, m, ...)   _nx_sequence_5(0, h, m, __VA_ARGS__) h(c, m, 6, __VA_ARGS__)
#define _nx_sequence_7(c, h, m, ...)   _nx_sequence_6(0, h, m, __VA_ARGS__) h(c, m, 7, __VA_ARGS__)
#define _nx_sequence_8(c, h, m, ...)   _nx_sequence_7(0, h, m, __VA_ARGS__) h(c, m, 8, __VA_ARGS__)
#define _nx_sequence_9(c, h, m, ...)   _nx_sequence_8(0, h, m, __VA_ARGS__) h(c, m, 9, __VA_ARGS__)
#define _nx_sequence_10(c, h, m, ...)  _nx_sequence_9(0, h, m, __VA_ARGS__) h(c, m, 10, __VA_ARGS__)
#define _nx_sequence_11(c, h, m, ...)  _nx_sequence_10(0, h, m, __VA_ARGS__) h(c, m, 11, __VA_ARGS__)
#define _nx_sequence_12(c, h, m, ...)  _nx_sequence_11(0, h, m, __VA_ARGS__) h(c, m, 12, __VA_ARGS__)
#define _nx_sequence_13(c, h, m, ...)  _nx_sequence_12(0, h, m, __VA_ARGS__) h(c, m, 13, __VA_ARGS__)
#define _nx_sequence_14(c, h, m, ...)  _nx_sequence_13(0, h, m, __VA_ARGS__) h(c, m, 14, __VA_ARGS__)
#define _nx_sequence_15(c, h, m, ...)  _nx_sequence_14(0, h, m, __VA_ARGS__) h(c, m, 15, __VA_ARGS__)
#define _nx_sequence_16(c, h, m, ...)  _nx_sequence_15(0, h, m, __VA_ARGS__) h(c, m, 16, __VA_ARGS__)
#define _nx_sequence_17(c, h, m, ...)  _nx_sequence_16(0, h, m, __VA_ARGS__) h(c, m, 17, __VA_ARGS__)
#define _nx_sequence_18(c, h, m, ...)  _nx_sequence_17(0, h, m, __VA_ARGS__) h(c, m, 18, __VA_ARGS__)
#define _nx_sequence_19(c, h, m, ...)  _nx_sequence_18(0, h, m, __VA_ARGS__) h(c, m, 19, __VA_ARGS__)
#define _nx_sequence_20(c, h, m, ...)  _nx_sequence_19(0, h, m, __VA_ARGS__) h(c, m, 20, __VA_ARGS__)
#define _nx_sequence_21(c, h, m, ...)  _nx_sequence_20(0, h, m, __VA_ARGS__) h(c, m, 21, __VA_ARGS__)
#define _nx_sequence_22(c, h, m, ...)  _nx_sequence_21(0, h, m, __VA_ARGS__) h(c, m, 22, __VA_ARGS__)
#define _nx_sequence_23(c, h, m, ...)  _nx_sequence_22(0, h, m, __VA_ARGS__) h(c, m, 23, __VA_ARGS__)
#define _nx_sequence_24(c, h, m, ...)  _nx_sequence_23(0, h, m, __VA_ARGS__) h(c, m, 24, __VA_ARGS__)
#define _nx_sequence_25(c, h, m, ...)  _nx_sequence_24(0, h, m, __VA_ARGS__) h(c, m, 25, __VA_ARGS__)
#define _nx_sequence_26(c, h, m, ...)  _nx_sequence_25(0, h, m, __VA_ARGS__) h(c, m, 26, __VA_ARGS__)
#define _nx_sequence_27(c, h, m, ...)  _nx_sequence_26(0, h, m, __VA_ARGS__) h(c, m, 27, __VA_ARGS__)
#define _nx_sequence_28(c, h, m, ...)  _nx_sequence_27(0, h, m, __VA_ARGS__) h(c, m, 28, __VA_ARGS__)
#define _nx_sequence_29(c, h, m, ...)  _nx_sequence_28(0, h, m, __VA_ARGS__) h(c, m, 29, __VA_ARGS__)
#define _nx_sequence_30(c, h, m, ...)  _nx_sequence_29(0, h, m, __VA_ARGS__) h(c, m, 30, __VA_ARGS__)
#define _nx_sequence_31(c, h, m, ...)  _nx_sequence_30(0, h, m, __VA_ARGS__) h(c, m, 31, __VA_ARGS__)
#define _nx_sequence_32(c, h, m, ...)  _nx_sequence_31(0, h, m, __VA_ARGS__) h(c, m, 32, __VA_ARGS__)
#define _nx_sequence_33(c, h, m, ...)  _nx_sequence_32(0, h, m, __VA_ARGS__) h(c, m, 33, __VA_ARGS__)
#define _nx_sequence_34(c, h, m, ...)  _nx_sequence_33(0, h, m, __VA_ARGS__) h(c, m, 34, __VA_ARGS__)
#define _nx_sequence_35(c, h, m, ...)  _nx_sequence_34(0, h, m, __VA_ARGS__) h(c, m, 35, __VA_ARGS__)
#define _nx_sequence_36(c, h, m, ...)  _nx_sequence_35(0, h, m, __VA_ARGS__) h(c, m, 36, __VA_ARGS__)
#define _nx_sequence_37(c, h, m, ...)  _nx_sequence_36(0, h, m, __VA_ARGS__) h(c, m, 37, __VA_ARGS__)
#define _nx_sequence_38(c, h, m, ...)  _nx_sequence_37(0, h, m, __VA_ARGS__) h(c, m, 38, __VA_ARGS__)
#define _nx_sequence_39(c, h, m, ...)  _nx_sequence_38(0, h, m, __VA_ARGS__) h(c, m, 39, __VA_ARGS__)
#define _nx_sequence_40(c, h, m, ...)  _nx_sequence_39(0, h, m, __VA_ARGS__) h(c, m, 40, __VA_ARGS__)
#define _nx_sequence_41(c, h, m, ...)  _nx_sequence_40(0, h, m, __VA_ARGS__) h(c, m, 41, __VA_ARGS__)
#define _nx_sequence_42(c, h, m, ...)  _nx_sequence_41(0, h, m, __VA_ARGS__) h(c, m, 42, __VA_ARGS__)
#define _nx_sequence_43(c, h, m, ...)  _nx_sequence_42(0, h, m, __VA_ARGS__) h(c, m, 43, __VA_ARGS__)
#define _nx_sequence_44(c, h, m, ...)  _nx_sequence_43(0, h, m, __VA_ARGS__) h(c, m, 44, __VA_ARGS__)
#define _nx_sequence_45(c, h, m, ...)  _nx_sequence_44(0, h, m, __VA_ARGS__) h(c, m, 45, __VA_ARGS__)
#define _nx_sequence_46(c, h, m, ...)  _nx_sequence_45(0, h, m, __VA_ARGS__) h(c, m, 46, __VA_ARGS__)
#define _nx_sequence_47(c, h, m, ...)  _nx_sequence_46(0, h, m, __VA_ARGS__) h(c, m, 47, __VA_ARGS__)
#define _nx_sequence_48(c, h, m, ...)  _nx_sequence_47(0, h, m, __VA_ARGS__) h(c, m, 48, __VA_ARGS__)
#define _nx_sequence_49(c, h, m, ...)  _nx_sequence_48(0, h, m, __VA_ARGS__) h(c, m, 49, __VA_ARGS__)
#define _nx_sequence_50(c, h, m, ...)  _nx_sequence_49(0, h, m, __VA_ARGS__) h(c, m, 50, __VA_ARGS__)
#define _nx_sequence_51(c, h, m, ...)  _nx_sequence_50(0, h, m, __VA_ARGS__) h(c, m, 51, __VA_ARGS__)
#define _nx_sequence_52(c, h, m, ...)  _nx_sequence_51(0, h, m, __VA_ARGS__) h(c, m, 52, __VA_ARGS__)
#define _nx_sequence_53(c, h, m, ...)  _nx_sequence_52(0, h, m, __VA_ARGS__) h(c, m, 53, __VA_ARGS__)
#define _nx_sequence_54(c, h, m, ...)  _nx_sequence_53(0, h, m, __VA_ARGS__) h(c, m, 54, __VA_ARGS__)
#define _nx_sequence_55(c, h, m, ...)  _nx_sequence_54(0, h, m, __VA_ARGS__) h(c, m, 55, __VA_ARGS__)
#define _nx_sequence_56(c, h, m, ...)  _nx_sequence_55(0, h, m, __VA_ARGS__) h(c, m, 56, __VA_ARGS__)
#define _nx_sequence_57(c, h, m, ...)  _nx_sequence_56(0, h, m, __VA_ARGS__) h(c, m, 57, __VA_ARGS__)
#define _nx_sequence_58(c, h, m, ...)  _nx_sequence_57(0, h, m, __VA_ARGS__) h(c, m, 58, __VA_ARGS__)
#define _nx_sequence_59(c, h, m, ...)  _nx_sequence_58(0, h, m, __VA_ARGS__) h(c, m, 59, __VA_ARGS__)
#define _nx_sequence_60(c, h, m, ...)  _nx_sequence_59(0, h, m, __VA_ARGS__) h(c, m, 60, __VA_ARGS__)
#define _nx_sequence_61(c, h, m, ...)  _nx_sequence_60(0, h, m, __VA_ARGS__) h(c, m, 61, __VA_ARGS__)
#define _nx_sequence_62(c, h, m, ...)  _nx_sequence_61(0, h, m, __VA_ARGS__) h(c, m, 62, __VA_ARGS__)
#define _nx_sequence_63(c, h, m, ...)  _nx_sequence_62(0, h, m, __VA_ARGS__) h(c, m, 63, __VA_ARGS__)
#define _nx_sequence_64(c, h, m, ...)  _nx_sequence_63(0, h, m, __VA_ARGS__) h(c, m, 64, __VA_ARGS__)

#define NX_LIMITS_SEQUENCE 64

#endif //NX_MACRO_ITERATE_64_HPP
