//
// Created by nexie on 21.12.2025.
//

#ifndef NX_MACRO_WHILE_64_HPP
#define NX_MACRO_WHILE_64_HPP

#ifndef NX_MACRO_PRIVATE_INCLUDE
    #error "This file was not meant to be included directly. Include <nx/macro/detail/while_limit.hpp> instead"
#endif

 # define _nx_while_0(c, o, r, ...) _nx_while_0_c(c(1, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_0_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_1(c, o, r, o(1, __VA_ARGS__)), r(1, __VA_ARGS__))
 # define _nx_while_1(c, o, r, ...) _nx_while_1_c(c(2, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_1_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_2(c, o, r, o(2, __VA_ARGS__)), r(2, __VA_ARGS__))
 # define _nx_while_2(c, o, r, ...) _nx_while_2_c(c(3, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_2_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_3(c, o, r, o(3, __VA_ARGS__)), r(3, __VA_ARGS__))
 # define _nx_while_3(c, o, r, ...) _nx_while_3_c(c(4, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_3_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_4(c, o, r, o(4, __VA_ARGS__)), r(4, __VA_ARGS__))
 # define _nx_while_4(c, o, r, ...) _nx_while_4_c(c(5, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_4_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_5(c, o, r, o(5, __VA_ARGS__)), r(5, __VA_ARGS__))
 # define _nx_while_5(c, o, r, ...) _nx_while_5_c(c(6, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_5_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_6(c, o, r, o(6, __VA_ARGS__)), r(6, __VA_ARGS__))
 # define _nx_while_6(c, o, r, ...) _nx_while_6_c(c(7, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_6_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_7(c, o, r, o(7, __VA_ARGS__)), r(7, __VA_ARGS__))
 # define _nx_while_7(c, o, r, ...) _nx_while_7_c(c(8, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_7_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_8(c, o, r, o(8, __VA_ARGS__)), r(8, __VA_ARGS__))
 # define _nx_while_8(c, o, r, ...) _nx_while_8_c(c(9, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_8_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_9(c, o, r, o(9, __VA_ARGS__)), r(9, __VA_ARGS__))
 # define _nx_while_9(c, o, r, ...) _nx_while_9_c(c(10, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_9_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_10(c, o, r, o(10, __VA_ARGS__)), r(10, __VA_ARGS__))
 # define _nx_while_10(c, o, r, ...) _nx_while_10_c(c(11, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_10_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_11(c, o, r, o(11, __VA_ARGS__)), r(11, __VA_ARGS__))
 # define _nx_while_11(c, o, r, ...) _nx_while_11_c(c(12, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_11_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_12(c, o, r, o(12, __VA_ARGS__)), r(12, __VA_ARGS__))
 # define _nx_while_12(c, o, r, ...) _nx_while_12_c(c(13, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_12_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_13(c, o, r, o(13, __VA_ARGS__)), r(13, __VA_ARGS__))
 # define _nx_while_13(c, o, r, ...) _nx_while_13_c(c(14, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_13_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_14(c, o, r, o(14, __VA_ARGS__)), r(14, __VA_ARGS__))
 # define _nx_while_14(c, o, r, ...) _nx_while_14_c(c(15, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_14_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_15(c, o, r, o(15, __VA_ARGS__)), r(15, __VA_ARGS__))
 # define _nx_while_15(c, o, r, ...) _nx_while_15_c(c(16, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_15_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_16(c, o, r, o(16, __VA_ARGS__)), r(16, __VA_ARGS__))
 # define _nx_while_16(c, o, r, ...) _nx_while_16_c(c(17, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_16_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_17(c, o, r, o(17, __VA_ARGS__)), r(17, __VA_ARGS__))
 # define _nx_while_17(c, o, r, ...) _nx_while_17_c(c(18, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_17_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_18(c, o, r, o(18, __VA_ARGS__)), r(18, __VA_ARGS__))
 # define _nx_while_18(c, o, r, ...) _nx_while_18_c(c(19, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_18_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_19(c, o, r, o(19, __VA_ARGS__)), r(19, __VA_ARGS__))
 # define _nx_while_19(c, o, r, ...) _nx_while_19_c(c(20, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_19_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_20(c, o, r, o(20, __VA_ARGS__)), r(20, __VA_ARGS__))
 # define _nx_while_20(c, o, r, ...) _nx_while_20_c(c(21, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_20_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_21(c, o, r, o(21, __VA_ARGS__)), r(21, __VA_ARGS__))
 # define _nx_while_21(c, o, r, ...) _nx_while_21_c(c(22, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_21_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_22(c, o, r, o(22, __VA_ARGS__)), r(22, __VA_ARGS__))
 # define _nx_while_22(c, o, r, ...) _nx_while_22_c(c(23, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_22_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_23(c, o, r, o(23, __VA_ARGS__)), r(23, __VA_ARGS__))
 # define _nx_while_23(c, o, r, ...) _nx_while_23_c(c(24, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_23_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_24(c, o, r, o(24, __VA_ARGS__)), r(24, __VA_ARGS__))
 # define _nx_while_24(c, o, r, ...) _nx_while_24_c(c(25, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_24_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_25(c, o, r, o(25, __VA_ARGS__)), r(25, __VA_ARGS__))
 # define _nx_while_25(c, o, r, ...) _nx_while_25_c(c(26, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_25_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_26(c, o, r, o(26, __VA_ARGS__)), r(26, __VA_ARGS__))
 # define _nx_while_26(c, o, r, ...) _nx_while_26_c(c(27, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_26_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_27(c, o, r, o(27, __VA_ARGS__)), r(27, __VA_ARGS__))
 # define _nx_while_27(c, o, r, ...) _nx_while_27_c(c(28, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_27_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_28(c, o, r, o(28, __VA_ARGS__)), r(28, __VA_ARGS__))
 # define _nx_while_28(c, o, r, ...) _nx_while_28_c(c(29, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_28_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_29(c, o, r, o(29, __VA_ARGS__)), r(29, __VA_ARGS__))
 # define _nx_while_29(c, o, r, ...) _nx_while_29_c(c(30, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_29_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_30(c, o, r, o(30, __VA_ARGS__)), r(30, __VA_ARGS__))
 # define _nx_while_30(c, o, r, ...) _nx_while_30_c(c(31, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_30_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_31(c, o, r, o(31, __VA_ARGS__)), r(31, __VA_ARGS__))
 # define _nx_while_31(c, o, r, ...) _nx_while_31_c(c(32, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_31_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_32(c, o, r, o(32, __VA_ARGS__)), r(32, __VA_ARGS__))
 # define _nx_while_32(c, o, r, ...) _nx_while_32_c(c(33, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_32_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_33(c, o, r, o(33, __VA_ARGS__)), r(33, __VA_ARGS__))
 # define _nx_while_33(c, o, r, ...) _nx_while_33_c(c(34, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_33_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_34(c, o, r, o(34, __VA_ARGS__)), r(34, __VA_ARGS__))
 # define _nx_while_34(c, o, r, ...) _nx_while_34_c(c(35, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_34_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_35(c, o, r, o(35, __VA_ARGS__)), r(35, __VA_ARGS__))
 # define _nx_while_35(c, o, r, ...) _nx_while_35_c(c(36, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_35_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_36(c, o, r, o(36, __VA_ARGS__)), r(36, __VA_ARGS__))
 # define _nx_while_36(c, o, r, ...) _nx_while_36_c(c(37, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_36_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_37(c, o, r, o(37, __VA_ARGS__)), r(37, __VA_ARGS__))
 # define _nx_while_37(c, o, r, ...) _nx_while_37_c(c(38, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_37_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_38(c, o, r, o(38, __VA_ARGS__)), r(38, __VA_ARGS__))
 # define _nx_while_38(c, o, r, ...) _nx_while_38_c(c(39, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_38_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_39(c, o, r, o(39, __VA_ARGS__)), r(39, __VA_ARGS__))
 # define _nx_while_39(c, o, r, ...) _nx_while_39_c(c(40, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_39_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_40(c, o, r, o(40, __VA_ARGS__)), r(40, __VA_ARGS__))
 # define _nx_while_40(c, o, r, ...) _nx_while_40_c(c(41, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_40_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_41(c, o, r, o(41, __VA_ARGS__)), r(41, __VA_ARGS__))
 # define _nx_while_41(c, o, r, ...) _nx_while_41_c(c(42, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_41_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_42(c, o, r, o(42, __VA_ARGS__)), r(42, __VA_ARGS__))
 # define _nx_while_42(c, o, r, ...) _nx_while_42_c(c(43, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_42_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_43(c, o, r, o(43, __VA_ARGS__)), r(43, __VA_ARGS__))
 # define _nx_while_43(c, o, r, ...) _nx_while_43_c(c(44, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_43_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_44(c, o, r, o(44, __VA_ARGS__)), r(44, __VA_ARGS__))
 # define _nx_while_44(c, o, r, ...) _nx_while_44_c(c(45, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_44_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_45(c, o, r, o(45, __VA_ARGS__)), r(45, __VA_ARGS__))
 # define _nx_while_45(c, o, r, ...) _nx_while_45_c(c(46, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_45_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_46(c, o, r, o(46, __VA_ARGS__)), r(46, __VA_ARGS__))
 # define _nx_while_46(c, o, r, ...) _nx_while_46_c(c(47, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_46_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_47(c, o, r, o(47, __VA_ARGS__)), r(47, __VA_ARGS__))
 # define _nx_while_47(c, o, r, ...) _nx_while_47_c(c(48, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_47_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_48(c, o, r, o(48, __VA_ARGS__)), r(48, __VA_ARGS__))
 # define _nx_while_48(c, o, r, ...) _nx_while_48_c(c(49, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_48_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_49(c, o, r, o(49, __VA_ARGS__)), r(49, __VA_ARGS__))
 # define _nx_while_49(c, o, r, ...) _nx_while_49_c(c(50, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_49_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_50(c, o, r, o(50, __VA_ARGS__)), r(50, __VA_ARGS__))
 # define _nx_while_50(c, o, r, ...) _nx_while_50_c(c(51, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_50_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_51(c, o, r, o(51, __VA_ARGS__)), r(51, __VA_ARGS__))
 # define _nx_while_51(c, o, r, ...) _nx_while_51_c(c(52, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_51_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_52(c, o, r, o(52, __VA_ARGS__)), r(52, __VA_ARGS__))
 # define _nx_while_52(c, o, r, ...) _nx_while_52_c(c(53, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_52_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_53(c, o, r, o(53, __VA_ARGS__)), r(53, __VA_ARGS__))
 # define _nx_while_53(c, o, r, ...) _nx_while_53_c(c(54, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_53_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_54(c, o, r, o(54, __VA_ARGS__)), r(54, __VA_ARGS__))
 # define _nx_while_54(c, o, r, ...) _nx_while_54_c(c(55, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_54_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_55(c, o, r, o(55, __VA_ARGS__)), r(55, __VA_ARGS__))
 # define _nx_while_55(c, o, r, ...) _nx_while_55_c(c(56, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_55_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_56(c, o, r, o(56, __VA_ARGS__)), r(56, __VA_ARGS__))
 # define _nx_while_56(c, o, r, ...) _nx_while_56_c(c(57, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_56_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_57(c, o, r, o(57, __VA_ARGS__)), r(57, __VA_ARGS__))
 # define _nx_while_57(c, o, r, ...) _nx_while_57_c(c(58, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_57_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_58(c, o, r, o(58, __VA_ARGS__)), r(58, __VA_ARGS__))
 # define _nx_while_58(c, o, r, ...) _nx_while_58_c(c(59, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_58_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_59(c, o, r, o(59, __VA_ARGS__)), r(59, __VA_ARGS__))
 # define _nx_while_59(c, o, r, ...) _nx_while_59_c(c(60, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_59_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_60(c, o, r, o(60, __VA_ARGS__)), r(60, __VA_ARGS__))
 # define _nx_while_60(c, o, r, ...) _nx_while_60_c(c(61, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_60_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_61(c, o, r, o(61, __VA_ARGS__)), r(61, __VA_ARGS__))
 # define _nx_while_61(c, o, r, ...) _nx_while_61_c(c(62, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_61_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_62(c, o, r, o(62, __VA_ARGS__)), r(62, __VA_ARGS__))
 # define _nx_while_62(c, o, r, ...) _nx_while_62_c(c(63, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_62_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_63(c, o, r, o(63, __VA_ARGS__)), r(63, __VA_ARGS__))
 # define _nx_while_63(c, o, r, ...) _nx_while_63_c(c(64, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_63_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_64(c, o, r, o(64, __VA_ARGS__)), r(64, __VA_ARGS__))
 # define _nx_while_64(c, o, r, ...) _nx_while_64_c(c(65, __VA_ARGS__), c, o, r, __VA_ARGS__)
 # define _nx_while_64_c(p, c, o, r, ...) _nx_logic_if(p)(_nx_while_65(c, o, r, o(65, __VA_ARGS__)), r(65, __VA_ARGS__))

#define NX_LIMITS_WHILE 64

#endif //WHILE_64_HPP
