//
// Created by nexie on 21.12.2025.
//

#ifndef WHILE_64_HPP
#define WHILE_64_HPP

#define _nx_while_0(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_1(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_1(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_2(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_2(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_3(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_3(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_4(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_4(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_5(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_5(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_6(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_6(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_7(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_7(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_8(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_8(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_9(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_9(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_10(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_10(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_11(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_11(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_12(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_12(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_13(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_13(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_14(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_14(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_15(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_15(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_16(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_16(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_17(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_17(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_18(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_18(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_19(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_19(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_20(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_20(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_21(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_21(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_22(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_22(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_23(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_23(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_24(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_24(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_25(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_25(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_26(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_26(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_27(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_27(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_28(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_28(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_29(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_29(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_30(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_30(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_31(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_31(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_32(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_32(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_33(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_33(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_34(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_34(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_35(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_35(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_36(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_36(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_37(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_37(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_38(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_38(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_39(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_39(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_40(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_40(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_41(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_41(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_42(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_42(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_43(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_43(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_44(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_44(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_45(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_45(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_46(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_46(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_47(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_47(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_48(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_48(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_49(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_49(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_50(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_50(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_51(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_51(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_52(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_52(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_53(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_53(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_54(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_54(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_55(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_55(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_56(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_56(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_57(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_57(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_58(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_58(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_59(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_59(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_60(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_60(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_61(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_61(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_62(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_62(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_63(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_63(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_64(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))
#define _nx_while_64(c, o, r, ...) _nx_logic_if(c(__VA_ARGS__))(_nx_while_65(c, o, r, o(__VA_ARGS__)), r(__VA_ARGS__))

#define NX_LIMITS_WHILE 64

#endif //WHILE_64_HPP
