include(nxConfigureComponent)
include(nxConfigureTest)
include(nxConfigureDemo)
include(nxCMakeLogScope)
include(nxMakeModule)
include(nxMakeModuleVersion)
include(nxParseOptions)
include(nxVersionInfo)